### ISSUE TITLE
command 'ForceCode.showMenu' not found

### ISSUE THREAD

**Issue by bwind-eb** [daishi4u/ForceCode#10]
Unable to run this update in VSCode 1.25. Downgraded to 1.24 and am still running into this error.

**Comment by julesx** [comment]
Uninstall all the salesforce extensions. Make sure they are actually removed from the extensions folder for vs code. Make sure there aren’t any leftovers from original force code. It should work fine.

**Comment by ennoucas** [comment]
I tried everything.. cleaning the folder, getting back to VS 1.24 version, trying v3.3.3 and 3.3.2. Each time I run the force menu command it says to download Java 8. I'm on Java 10 and have the development kit installed as well. 

I'm on OS X Sierra.

**Comment by JimCotter** [comment]
@ennoucas any ideas what that should look like in windows? Found the jdk folder of course but see no reference to /contents/home
![image](https://user-images.githubusercontent.com/41166001/42763288-362d137a-88d8-11e8-8d97-d16f9680f7d3.png)

**Comment by JimCotter** [comment]
Also @ennoucas in my 1.24 version, this setting is null and the menus work fine. You're saying if you populate it in 1.25+ the menus work again?

**Comment by AndreyMargalik** [comment]
@JimCotter 
Hi! 
On Windows you have to simply write path to Java home directory.
In your case it would look like:
"salesforcedx-vscode-apex.java.home": "c:\\Program Files\\Java\\jdk1.8.0_121"

Hope this would help to win your struggle :)

**Comment by hwong103** [comment]
@AndreyMargalik thanks! this helped me with this error

**Comment by eltoroit** [comment]
Thanks, @ennoucas. This worked for me. I am using VS Code v1.25 and ForceCode 3.5.2

**Comment by FBosler** [comment]
This seems like a really dumb question, but I am new to visual studio. How do I install this version of FoceCode?

**Comment by raghurankawat** [comment]
@FBosler 
- Download your desired ForceCode .vsix file. Like:
![image](https://user-images.githubusercontent.com/10707579/43715325-c3a0dfea-999d-11e8-86c8-33c3d2cbd2d1.png)

- Goto VSCode and choose install from VSIX
![](https://i.stack.imgur.com/yrAcy.png)

Cheers

**Comment by FBosler** [comment]
Well, that wasn't too hard 👍 much appreciated! I installed some "install from vsix package" first, which obviously didn't work ...

Thx mate

**Comment by FBosler** [comment]
But now I am getting: 
Java runtime could not be located. Set one using the salesforcedx-vscode-apex.java.home VS Code setting.

**Comment by hwong103** [comment]
This error has popped up again. I'm on 3.5.14 and was working fine yesterday. This morning I think there was an update (v43.11.0) to the Salesforce extensions and now the showMenu error occurs. 

Not sure if I can downgrade the SF extensions to test this...

**Comment by daishi4u** [comment]
This shouldn't be an error from 3.6.6 onward because I no longer require downloading the salesforce extensions so I'm closing this.

**Comment by daishi4u** [comment]
@npathuri0531 I would recommend upgrading to the newest version (v3.8.3) and you won't face this issue anymore. Before you do though, please read the readme very carefully, as a LOT has changed since that version

**Comment by daishi4u** [comment]
@npathuri0531 you will need to log out through the forcecode menu then log back in

**Comment by npathuri0531** [comment]
@daishi4u Thanks so much.It works. Is there a way it can get refresh token automatically (if needed) every time save happens (similar to how mavens mate works)? It may be difficult to log out and login back for every few hours. Thoughts please?

**Comment by dmgerow** [comment]
@npathuri0531 I just quit VSCode and re-open it and it refreshes fine

**Comment by daishi4u** [comment]
@npathuri0531 Right off the top of my head all I can give you is a maybe. I have an idea of how to do it, but not sure if it will work or not. I'm going to open a separate issue for this so I'll remember and then look into it.

**Comment by npathuri0531** [comment]
@daishi4u @dmgerow, Thanks so much. I have been a great fan of MavensMate and I am switching to VSCode using ForceCode. I can't express how well I am liking it so far. Great work.

**Comment by daishi4u** [comment]
@npathuri0531 Glad you're liking it so far. I fell in love with it pretty soon after using it for the first time, then I found out celador (The original author) wasn't going to support it anymore so I just had to keep it going because there's so much potential. Anyways, if you face anymore issues then don't be afraid to create a new issue. Enjoy!
