### ISSUE TITLE
ForceCode Menu commands not working

### ISSUE THREAD

**Issue by RobertCollinsCauseview** [daishi4u/ForceCode#100]
**Describe the bug**
I am not sure what I did to have this issue occur as it began seemingly randomly. However, the exact issue is that when I open my VSCode, ForceCode starts fine and displays the that I have files that are changed on server (15 of them if it matters). If I click refresh on any of them nothing happens and "Modified File" sits in the Running Tasks section of ForceCode. If I dismiss them they do get removed from the Running Tasks. When I try to use any commands inside the ForceCode Menu nothing happens. When I use the command "ForceCode: Open Org In Browser" that is not in the ForceCode Menu it works.

**To Reproduce**
1. Open a project and sign in when prompted
2. Open ForceCode Menu
3. Try to use any command in the menu
4. Nothing happens

(This also affects my ability to Ctrl+Shift+s to the compile on server.)

**Screenshots**
![forcecodecommandnotworking](https://user-images.githubusercontent.com/19689386/46025935-1134f980-c0b8-11e8-8397-2f41f51d1622.gif)

**Desktop:**
 - OS: Windows 64 bit
 - Browser: Google Chrome
 - Version: 69.0.3497.100
 - ForceCode Version: 3.9.1

**Comment by tomas-migra** [comment]
I installed 3.9.2 and same issue occurred to me as well before I user 3.9.1 and it worked fine. I will try to downgrade to 3.9.0

**Comment by daishi4u** [comment]
Strange, nothing changed between 3.9.0 and 3.9.1 that would have effected using the menu

**Comment by RobertCollinsCauseview** [comment]
Unfortunately updating to version 3.9.2 has the same issue occurring.

**Comment by daishi4u** [comment]
OK everyone can you post the last working version that each of you used?

**Comment by daishi4u** [comment]
Can I also get you guys to try something for me. Will you open a file in your project after starting vscode, not from the forcecode menu, just open one from the explorer. Now leave that file open and close vscode then start it again. Do you still have the same issue after this? If this solved the issue then let me know because I know exactly where the problem is then. Thanks everyone

**Comment by RobertCollinsCauseview** [comment]
I believe the last working version I had was version 3.8.7.

So I did 2 things, I deleted everything in my workspace other than my src folder. Then I opened VSCode and opened ForceCode Menu. When I clicked refresh on all the items that show changes only one actually refreshed. I decided to try what you suggested and left the file I wanted to save up open and restarted. When I opened VSCode again, ForceCode show the files I need to refresh again and properly refreshed. It seems to be working again now even if I open a file that wasn't open before. I will try restarting it and everything again before I leave work today to see if it is still working on a restart and such.

**Comment by daishi4u** [comment]
Can any of you try out this pre-release to see if it solves your issue: https://github.com/daishi4u/ForceCode/raw/testing-menu-fix/forcecode-3.9.3-b1.vsix

**Comment by tomas-migra** [comment]
I tried 3.9.9-b1 and no change for me

**Comment by daishi4u** [comment]
OK, well I need to know what the error is then. Someone needs to test with the developer tools in vscode open so they can view any errors that are printed to the console, otherwise I won't be able to get this fixed because I haven't been able to reproduce this issue on my end and I've tested on Linux, windows 7 and windows 10. Thanks

**Comment by rock-pile** [comment]
Same issue here..

**Comment by tomas-migra** [comment]
Are you guys using sfdx cli in vscode? I created new project by forcecode only in new folder and now it works. Only thing changed is that .sfdx folder now is missing

**Comment by daishi4u** [comment]
Forcecode works alongside of the sfdx extensions and will actually create the sfdx folder if it doesn't exist for code completion separate on each org, so that folder being gone has nothing to do with the problem. Could solve it if someone would look at the developer tools in vscode while facing the problem, but until then I can't fix it

**Comment by raghurankawat** [comment]
Just to add ...I faced the same issue in 3.9.1 once. I tried different things to resolve but nothing worked. Then I deleted .sfdx/tools/apex.db and tried and it was working as expected.

**Comment by torcu** [comment]
same issue using 3.9.0 
Also 15 files in runing tasks (they do get updated in my local).
I have noticed this since I use ForceCode along with version control (probably nothing to do with it)
No errors shown  in the developer tools.

![screenshot_4](https://user-images.githubusercontent.com/4548947/46193482-a0cbe980-c2fe-11e8-8c16-7514c8f8bc6a.png)

![screenshot_5](https://user-images.githubusercontent.com/4548947/46194330-6c0d6180-c301-11e8-9052-455935f43017.png)

**Comment by torcu** [comment]
> Forcecode works alongside of the sfdx extensions and will actually create the sfdx folder if it doesn't exist for code completion separate on each org, so that folder being gone has nothing to do with the problem. Could solve it if someone would look at the developer tools in vscode while facing the problem, but until then I can't fix it

- Tried deleting  .sfdx/tools/apex.db . It doesn't seem to fix the problem
- Tried again with a different org but now I can see some errors in the console:

![screenshot_6](https://user-images.githubusercontent.com/4548947/46195098-9c55ff80-c303-11e8-915d-0b5ee415ebe1.png)

**Comment by fabianPas** [comment]
I'm having the same issue exactly as described here.

**Comment by daishi4u** [comment]
OK, when you guys face the error, can you open the output panel and view the output from the apex language server?

**Comment by torcu** [comment]
No errors in there., btw I've downgraded to 8.3.7 and it doesnt work. 

![screenshot_7](https://user-images.githubusercontent.com/4548947/46209719-e30d1f00-c32e-11e8-8810-5620b3e0ae87.png)

**Comment by daishi4u** [comment]
Do you guys have anything extra in your force.json or something misspelled by chance?

**Comment by daishi4u** [comment]
You can all try 3.9.3 and see if it will work for you, but please answer the previous question as well. Thanks

**Comment by torcu** [comment]
> Do you guys have anything extra in your force.json or something misspelled by chance?

Hi

I don't think so, I've got the file created and didn't change it: just in case:

{
    "apiVersion": "43.0",
    "autoRefresh": false,
    "browser": "Google Chrome Canary",
    "checkForFileChanges": true,
    "debugFilter": "USER_DEBUG|FATAL_ERROR",
    "debugOnly": true,
    "deployOptions": {
        "allowMissingFiles": true,
        "checkOnly": false,
        "ignoreWarnings": true,
        "rollbackOnError": true,
        "runTests": [],
        "singlePackage": true,
        "testLevel": "NoTestRun",
        "purgeOnDelete": false
    },
    "maxFileChangeNotifications": 15,
    "overwritePackageXML": false,
    "poll": 1500,
    "pollTimeout": 1200,
    "prefix": "",
    "revealTestedClass": false,
    "showFilesOnOpen": true,
    "showFilesOnOpenMax": 3,
    "showTestCoverage": true,
    "showTestLog": true,
    "spaDist": "",
    "srcDefault": "",
    "srcs": {},
    "outputQueriesAsCSV": false,
    "src": "src",
    "url": "https://test.salesforce.com",
    "autoCompile": true,
    "username": "username@test"
}

**Comment by daishi4u** [comment]
Thanks @torcu, just want to cover all bases.

**Comment by torcu** [comment]
> You can all try 3.9.3 and see if it will work for you, but please answer the previous question as well. Thanks

This one works for me!
Cheers!

**Comment by daishi4u** [comment]
@RobertCollinsCauseview, @tomas-migra, @Xander567, @rock-pile, @raghurankawat, @fabianPas

Can you all try the newest version as well (3.9.3) and let me know, since @torcu says it works for them. Thanks everyone!

**Comment by tomas-migra** [comment]
Works for me as well

**Comment by raghurankawat** [comment]
@daishi4u  3.9.3 is working fine for me. Thanks
