### ISSUE TITLE
VisualForce Compile Error in Controller

### ISSUE THREAD

**Issue by mnunezdm** [daishi4u/ForceCode#102]
**Describe the bug**
When trying to deploy a VisualForce page with errors an unhandled error appears `Illegal value for 'line'`

I have found that these issues appear when the action of a commandLink can't be found in the controller, other simpler errors like, for example, when you forget to close a tag are being reported

Maybe it could be because the line in which SalesForce reports the error? Errors in controller/merge fields gets reported by salesforce at line 0, while other like missing end tag gets reported in the line that are supposed to be. Its seems to be some kind of OutOfIndex error where the plugin is trying to find the Line 0

### Error at line XX

<img width="1198" alt="screen shot 2018-09-30 at 19 45 20" src="https://user-images.githubusercontent.com/10410852/46260714-ce28bb00-c4e9-11e8-83be-22e1a2f79d25.png">

<img width="1084" alt="screen shot 2018-09-30 at 19 47 52" src="https://user-images.githubusercontent.com/10410852/46260711-c2d58f80-c4e9-11e8-83c2-4e9cb81e19e1.png">

### Error at line 0

<img width="1134" alt="screen shot 2018-09-30 at 19 45 39" src="https://user-images.githubusercontent.com/10410852/46260720-de409a80-c4e9-11e8-8235-e203e90a2e8f.png">

<img width="1416" alt="screen shot 2018-09-30 at 19 47 38" src="https://user-images.githubusercontent.com/10410852/46260729-07f9c180-c4ea-11e8-982d-956fac49fb09.png">

**To Reproduce**
1. Add a compilation error to a VisualForce Page
2. Compile it
3. An unhandled error appear

**Expected behavior**
The error should appear in the problems panel

**Screenshots**
![out](https://user-images.githubusercontent.com/10410852/46260237-afbfc100-c4e3-11e8-8a22-03b14187d46a.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 3.9.2

**Additional context**
NA

**Comment by daishi4u** [comment]
Thanks for reporting this and for the PR, I will look at it more in detail after work, but a quick glance I think it will work.
