### ISSUE TITLE
RFI: Code completion

### ISSUE THREAD

**Issue by FireWall84** [daishi4u/ForceCode#104]
I installed version 3.9.3 and via ForceCode Menu I selected Code Completion Refresh.
Now I have them in .sfdx>tools>sobjects>customObjects and >standardObjects, but if I want to use them they are not read somehow.
fi if I type Acc or List<Acc I would expect to see Account in the proposed list, but it isn't.
What I am doing wrong, or how does this work exactly?

**Comment by daishi4u** [comment]
You need to install the salesforce apex language server extension to get code completion and make sure you follow their instructions to install Java and stuff.

**Comment by FireWall84** [comment]
Today I arrived at the office. Launched VSC and I tried again and suddenly it was there. I guess it was some kind of caching error...
