### ISSUE TITLE
Running the contributed command:'ForceCode.showMenu' failed

### ISSUE THREAD

**Issue by rtanikella** [daishi4u/ForceCode#105]
**Describe the bug**
This might be an easy fix. I installed ForceCode for the very first time. I set my   "salesforcedx-vscode-apex.java.home" appropriately in User Settings. But when I bring up the command pallet and select "ForceCode: ForceCode Menu" I get the error "Running the contributed command:'ForceCode.showMenu' failed". The same occurs for "Login to an org" ("Running the contributed command:'ForceCode.login' failed.")

**To Reproduce**
1. Go to Command Pallete
2. "ForceCode: ForceCode Menu"
3. See error "Running the contributed command:'ForceCode.showMenu' failed"

**Expected behavior**
I expected to see the ForceCode menu

**Desktop (please complete the following information):**
 - OS: macOs 10.13.6
 - Browser Chrome 69.0.3497.100 (Official Build) (64-bit)
 - Version 3.9.3

**Additional context**
One odd thing I noticed is that when I try to get the ForceCode Menu from the command pallete the error text displays with the red 'x' error icon. When I use command-option-c the same error text displays with the yellow '!' warning icon. Curious, but it may mean nothing.

**Comment by daishi4u** [comment]
Please open a folder in vscode before trying any commands with forcecode

**Comment by rtanikella** [comment]
Thank you for the hint, that helped. And thank you for the work!
