### ISSUE TITLE
Local Host Error while connecting to a sandbox

### ISSUE THREAD

**Issue by npathuri0531** [daishi4u/ForceCode#107]
Hi Brett,

I am using ForceCode 3.9.6 version from market place. I am using company laptop. If I connect to company vpn network and try to connect to a new sandbox thru ForceCode , everything is working.

If I am not connected to company vpn and try to connect to a new sandbox , system is giving me localhost connection failure after entering user id, pwd. This error is coming during redirect.

URL of the redirect is looking like

http://localhost:1717/OauthRedirect?code=aPrxP0ISxL6m.okCjJSdQnbs1xiSkCVtF8tx8Hjm9x.eZDhHHzoqPwXNkej5nD9NLr5uCEs2bg%3D%3D&state=4fcd6b6a7fff

Not quite sure, what is causing the issue. Can you please help.

Chait

**Comment by npathuri0531** [comment]
Thanks Brett. I have tried it and got the same error with 1717. Attached is how my sfdx-project.json looks like.


    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com/",
    "sourceApiVersion": "43.0",
    "oauthLocalPort" : "2000"
}

**Comment by daishi4u** [comment]
OK, so are you behind a network proxy then? If so then refer to the post here https://github.com/daishi4u/ForceCode/issues/79
