### ISSUE TITLE
execute anonymous apex

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#11]
you are forced to select code, it does not seem to use the active text file like it says it does

also: when you run execute anonymous, you are taken to the output tab.  however, if you have syntax errors, the problems tab is actually what you want to see.  output has nothing in it.

**Comment by daishi4u** [comment]
I do have that in the readme. I removed the execute anon from files a long time ago. The only way to do it is to select text. Looks like I need to update the description....Thanks!

**Comment by julesx** [comment]
Boo. Active file is much nicer for a test bed style thing.
