### ISSUE TITLE
Running the contributed command:'ForceCode.showMenu' failed After Open .Vscode

### ISSUE THREAD

**Issue by sou-t** [daishi4u/ForceCode#111]
**Running the contributed command:'ForceCode.showMenu'**
Select ForceCode:FoeceCode Menu
Running the contributed command:'ForceCode.showMenu'

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser chrome

 VsCode Version 1.28.4
ENABLED
-Apex 0.0.2
-ForceCode 3.9.10

File
OpenForder
-Select [g:\....\.vscode](workspace folder)

View
-Command Palette
- ForceCode:FoeceCode Menu
pop Running the contributed command:'ForceCode.showMenu'
And Status ver display [Forcecode Loading...] <not Return...

Where Open Folder ?

Set WorkSpaveFolder   to  "D:\Vscode\.vscode"
Not Create  settings.json. file...

//////////////////////////////////////////////////////////////
UnInstall And ReInstall . but Do not improve.
Help.

**Comment by daishi4u** [comment]
This is fixed in the 3.9.11 marketplace version now
