### ISSUE TITLE
Deployment by package.xml fails

### ISSUE THREAD

**Issue by narekharutyunyan** [daishi4u/ForceCode#112]
**Describe the bug**
Deployment by package.xml fails with following message after 4-5 seconds - "Polling time out. Process Id = 0Af0v00000kKFAyCAO".

**To Reproduce**
1. Go to ForceCode menu and click Deploy Package
2. Click on 'Deploy from package.xml'
3. after 4-5 seconds it fails with error message(and it is to quick to really be a timeout)

**Expected behavior**
It would be great also to get more details information/feedback after deployment failed. In older versions it use to generate some deployment.xml  with detailed information about failure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 3.9.12

**Additional context**

**Comment by daishi4u** [comment]
Yes, this just means it timed out. You can view the progress in the deployments in setup in your org. I thought I had a nice feature to do this, but it must not be working correctly. I will add it in the next release. Just so I'm clear, the deployment itself doesn't fail. It just takes longer than Forcecode is willing to wait.

**Comment by narekharutyunyan** [comment]
Thanks for the clarification. That would be a nice enhancement.  I've noticed one issue. When singlePackage flag is false(which is default value), the deployment fails with "No package.xml found" error message. Correct me if I'm wrong but looks like the deployment will fail if the project has only one package.xml in the folder and flag is unchecked. Please add the description of the flag as I couldn't find any information about this flag in the documentation.
