### ISSUE TITLE
ForceCode is deleting active scratch orgs

### ISSUE THREAD

**Issue by ennoucas** [daishi4u/ForceCode#113]
**Describe the bug**
I noticed a weird behaviour on projects where I was not using force code but using sfdx. My scratch orgs were always disappearing saying for example : *"No active scratch orgs found. Specify --all to see all scratch orgs"* whereas I knew I had one active. 

I discovered it is **Force Code** which deletes my scratch orgs: I opened my SFDX project on VS code where I don't have force code enabled. I created a new scratch org from my dev hub and could see it when doing "sfdx force:org:list". Then, I just launched the command ForceCode: ForceCode Menu which displays "Select a dev org or login to a new one...". I close it and then calling again "sfdx force:org:list" displays *"No active scratch orgs found. Specify --all to see all scratch orgs"*

**Desktop (please complete the following information):**
 - OS: OSX
 - Visual Studio Code
 - SFDX project without force code

**Comment by daishi4u** [comment]
Forcecode shouldn't be removing scratch orgs in the marketplace version. If you are using a version from this repo then it is outdated and you should upgrade
