### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by celador** [daishi4u/ForceCode#13]
Hello!  I see you've made some awesome changes to the extension!!!  This is awesome!

I have created a pull request at https://github.com/celador/ForceCode/pull/158 

Can you review it and make sure you agree with the changes?

I am in the process of reviewing the changes myself and would love it if we could collaborate on this to move this forward!   I will publish an update to the extension that includes your changes soon.  :) 

Cheers!

**Comment by daishi4u** [comment]
Thank you! I really appreciate you doing this :)
