### ISSUE TITLE
3.5.2 login to org bug

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#15]
made new vs code workspace
open force code menu
log in successfully

presented with following error:

![image](https://user-images.githubusercontent.com/3010047/42883570-f07fc0e6-8a69-11e8-8e42-1cc3a48185a8.png)

suggestion:

collapse the "ForceCode 3.5.2 connected" status bar item into something smaller, and put the full information in the tooltip. i have long emails and it takes up a 3rd of my status bar

**Comment by daishi4u** [comment]
I haven't seen this one. Will see if I can replicate it. As for the status bar info, that's a great idea...I'll see what I can do :)

**Comment by julesx** [comment]
try removing the `src `parameter from your force.json

i think that may be the root of a bunch of my issues
