### ISSUE TITLE
test result log just shows a blank editor window

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#17]
when i run a test via vs code, a pane appears with the .log file but it is empty

3.5.2

update: i notice now that the success/fail message goes to the output pane, but only if you have ForceCode selected from the associated dropdown.  it'd probably be nice if there was something more obvious telling you if it passed/failed.  i was expecting the .log file to show that information, but i guess that file only shows actual debug writes?

**Comment by daishi4u** [comment]
You can set the debug level in the force.json options. By default it only shows debug and fatal errors. If the test fails, a notification will popup, otherwise it will say all tests passed where it has your username on the status bar.

**Comment by julesx** [comment]
ok i see that now.  i sort of feel like both success and fail should display the same way.

the timer on the test passing is a bit short; a notification you are forced to dismiss would be better.  especially since tests can take a few minutes and it's easy to look away.

**Comment by daishi4u** [comment]
Version 3.5.3 should solve this problem

**Comment by julesx** [comment]
works great :+1:
