### ISSUE TITLE
Metadata Describe Error

### ISSUE THREAD

**Issue by aaronmorris** [daishi4u/ForceCode#18]
When I'm trying to deploy my javascript files from resources I keep getting the "Metadata Describe Error" message.  Apex classes appear to be deploying fine.

I'm running ForceCode 3.5.2 in VS Code 1.25.1

**Comment by daishi4u** [comment]
Could you give me some exact steps to replicate this error? Thank you :)

**Comment by aaronmorris** [comment]
This may be a one-off error based on a not so good practice from a previous developer.  

I have a javascript file in src/staticresources/file.resource.  Even though it is just javascript someone before me gave it a .reseource extension.  

It doesn't seem to be deploying at all when I save, but when I right click and go to Save/Compile/Deploy, I get an error message that says "Metadata Describe Error. Please try again."

**Comment by daishi4u** [comment]
Did you open this static resource from Salesforce(In ForceCode) or did you just put it into the project by copy and paste? If it's already in salesforce then you can just open it like you would an apex class and then it will put everything in the nameing convention that it needs to be in. Worst case scenario: Upload it manually through salesforce, then open it in ForceCode with the open command in the ForceCode menu. Then you should be able to deploy after edits by just saving the file.

**Comment by aaronmorris** [comment]
Looks like that worked.  Thanks.
