### ISSUE TITLE
can't compile/deploy files

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#2]
i was using the celador/ForceCode previously, and did not have this issue

every file i try to compile/deploy complains that "dependent class is invalid and needs recompilation"

sometimes it is the very file i am trying to upload, sometimes it is some other file referenced within.

in this case right now, the very class i am uploading is invalid with the error: "No such column 'Id' on entity 'User'", which is clearly false.

**Comment by daishi4u** [comment]
You successfully logged in with the browser?

**Comment by julesx** [comment]
yes.  i go through the login process in browser.  status bar says "connected as jules@myemail.com"

tried again right now, it just complains that some class is invalid and needs recompilation.

**Comment by daishi4u** [comment]
Interesting. What OS are you using? Any more details you can give me would be great, thanks.

**Comment by julesx** [comment]
Windows 7
I am not using a DX project 
Latest vs code
I do not have much experience with salesforce but my understanding is we have a fairly non standard folder setup, if perhaps you are expecting some things to exist in certain locations. 
I’ll reiterate that if I swap out to old force code the same files upload with no issues.

**Comment by julesx** [comment]
well something has changed but it still doesn't work

![image](https://user-images.githubusercontent.com/3010047/42399378-95dfcbae-813b-11e8-932a-f676394b9237.png)

now pops up when i try to compile/deploy

**Comment by julesx** [comment]
Reinstalled everything this morning and gave it another shot.

`Dependent class is invalid and needs recompilation: Class CalendarModelBase : Dependent class is invalid and needs recompilation: Class CoreController : Invalid type: Document`

**Comment by daishi4u** [comment]
Ok, going back to a previous comment of yours...you say that you have a pretty non-standard folder setup? Did you change the src option in the force.json to reflect your setup? If so, and it's still not working, then please send a screenshot of the folder setup that you are using. Thanks

**Comment by julesx** [comment]
this is actually what got it working

i use a VS Code workspace, and have added the "classes" folder directly to the workspace.  the "classes" folder lives inside a folder named "sfdc", which also contains folders for components, documents, objects, etc. 

i added src: "sfdc" to force.json and it is working now :)

**Comment by daishi4u** [comment]
Glad you got it figured out :) Going to close the issue now.

**Comment by julesx** [comment]
this is back for me with all versions.  i cannot save anything anymore :(
