### ISSUE TITLE
status bar suggestions

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#21]
i think the status bar can be improved. currently it utilizes 3 different status bar elements.  "executing tasks" is displayed in one element, but the result of that execution is displayed in another.

i believe everything should be condensed into one button.

the label on the button would be something like "ForceCode - connected (1408/15000)"

i don't think the version should be listed.  it is not important enough information.  

clicking the button opens the menu as it does now.

there is a spinning arrow loading indicator you can use to denote activity.  the VS Live Share extension uses it.  

triggering a ForceCode task displays the spinning arrow to the left of the text.  text on button changes to "ForceCode - saving"

when the task completes, text changes again:  "ForceCode - save complete" on a ~10 second timer before reverting to original.

**Comment by daishi4u** [comment]
This is what I was trying to get away from, as it's what the original extension used. I will think about it and maybe we can meet somewhere in the middle. I can agree with it taking up a lot of room though.

**Comment by daishi4u** [comment]
You'll like the new layout in 3.8.0...check it out

**Comment by julesx** [comment]
much improved, great work

small thing but i'd really like the little animated spinning arrows to denote activity instead of or in conjunction with the message that appears for eg when saving a class
