### ISSUE TITLE
conflict with apex replay debugger extension

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#24]
as soon as i start using apex replay debugger, forcecode stops working.

all the status bar items are gone, and trying to open the menu fails.

attached image: 
![image](https://user-images.githubusercontent.com/3010047/42964804-21652e7e-8b66-11e8-815f-ab5aff8c2d49.png)

i dont think this is true

**Comment by daishi4u** [comment]
Interesting. I've never used it so of course I've never seen the error. ForceCode doesn't depend on the replay debugger, so that is strange.

**Comment by daishi4u** [comment]
Ok everyone, pushing up 3.5.7 now which fixes this issue. You will need to add "sfdxCompatibility": true to your force.json file in order to use the other extensions.
