### ISSUE TITLE
Loop: You are not logged in. Login now?

### ISSUE THREAD

**Issue by hwong103** [daishi4u/ForceCode#26]
Hi 

I've recently decided to try using this version of ForceCode (you have no idea how excited I am), and updated to 1.25.1 VS Code along with it. 

I'm running into a weird issue where I can't log into my sandbox properly. When I select Yes it opens my browser to log into my org. Once logged in on the browser, the popup appears again asking me to login again.

Any ideas? I've disabled the original ForceCode extension prior to using this version.

Edit: Just to add I looked into my Login History and can see they're all successful

**Status | Application | Login URL |** 
Success | Global Connected App | test.salesforce.com | 
Success | Browser | test.salesforce.com |

**Comment by daishi4u** [comment]
I haven't ran into this problem yet. Have you been able to successfully login without this issue before?

**Comment by julesx** [comment]
is your browser forcing incognito maybe?

**Comment by hwong103** [comment]
> I haven't ran into this problem yet. Have you been able to successfully login without this issue before?
I've never used this version of ForceCode before. The OG ForceCode I could login fine but the login information was in the force.json file so I never had any issues there

>is your browser forcing incognito maybe?
Nah definitely in regular chrome as that was what I had open at the time. My chrome version is currently at Version 67.0.3396.99 (Official Build) (64-bit)

I've had to roll-back to 1.24.1 and OG ForceCode for the time being. Any ideas on how to debug this? Also when I rolled back I've realized that I've got the 32-bit version of VS Code installed. Could this be the culprit?

**Comment by eltoroit** [comment]
I am having the same issue, I added the password to the force.json configuration file and it works fine, but I want to stop using this anti-pattern. How does ForceCode receive the notification from Salesforce that the login was succesful?

**Comment by daishi4u** [comment]
It uses oauth2 authentication keys so once you log in and grant access, which I hope you did in the browser, then you will be logged in until you log out.

**Comment by daishi4u** [comment]
I'm using the salesforce cli to authenticate using the web authentication command, it handles the rest

**Comment by hwong103** [comment]
Seeing the comments made in Issue [#30](https://github.com/daishi4u/ForceCode/issues/30)

I've figured out why we're seeing this Loop issue. It's conflicting with the other Salesforce extensions. I've disabled everything and only enabled this version of ForceCode (and it's dependent extensions) and it now works perfectly.

**Comment by daishi4u** [comment]
Ok everyone, pushing up 3.5.7 now which fixes this issue. You will need to add "sfdxCompatibility": true to your force.json file in order to use the other extensions.
