### ISSUE TITLE
Invalid static resource folder or file name.

### ISSUE THREAD

**Issue by aaronmorris** [daishi4u/ForceCode#27]
When I try and save/deploy javascript files in a resource bundle, i get the follwoing error message:

> Invalid static resource folder or file name. Name must be in the form of ResourceName.resource.type.subtype EXAMPLE: MyResource.resource.aplication.javascript This folder would then contain one file, named MyResource.js

I'm not in a position where I can change the names of these files or directories.  Is there a workaround for this?

**Comment by daishi4u** [comment]
No, this is the only way that ForceCode is saving static resource files at the moment.

**Comment by aaronmorris** [comment]
Ok got it.  Are there any plans to remove this restriction in the future?

**Comment by daishi4u** [comment]
Not in the near future, no.
