### ISSUE TITLE
Can't log when SAML enabled

### ISSUE THREAD

**Issue by Bartheleway** [daishi4u/ForceCode#28]
Hi, thanks for the good work.

In my case, we connect to the production org with SAML (not with the standard salesforce login page). The issue is that some of the developers (like me), doesn't have a SAML access to the org. Instead we use the username, password and token url login. In the previous version I was able to log to that org using username, password and token. Now it tries to redirect me to the login page even if I'm already connected to the org in my browser.

Any ideas ?

**Comment by daishi4u** [comment]
Even if you're already connected in a browser it will still direct you to login through the browser. Have you tried to just login with the browser window that pops up with your username and password? If not, try it and let me know what happens...

**Comment by Bartheleway** [comment]
I did try and unfortunatly the login page is disabled for this org. That means that we can't login using the salesforce login page (even if I choose custom domain). Instead we use https://[domain].my.salesforce.com?un=[username]&pw=[password] to connect to this org in the browser

**Comment by daishi4u** [comment]
Did you ever figure anything out with this by chance?
