### ISSUE TITLE
feature request: multiple orgs

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#3]
oftentimes i have the need to upload files to two or three different orgs.

it would be nice if i could store the configurations for all my orgs, select a default org, as well as have the ability to change orgs on the fly.

currently one has to log out from current org and then log into new org (which is an improvement from original, as there one had to modify force.json file and then restart vscode)

**Comment by daishi4u** [comment]
The way that I do this is to make a vscode workspace for each org. Then you can even open two orgs at the same time in different instances of vscode. This also allows you to drag files from one to the other, which you should then be able to save to the other org

**Comment by daishi4u** [comment]
This is now implemented in v3.8.0. Please read through the README as a LOT has changed!!!
