### ISSUE TITLE
Overriding commands from salesforce.salesforcedx-vscode-core 

### ISSUE THREAD

**Issue by Codeneos** [daishi4u/ForceCode#30]
While I was testing your updated version of the ForceCode extension I noticed that it conflicts with the the salesforce provided ``salesforce.salesforcedx-vscode-core`` extension. 

In the past I was using both force code and the official Salesforce extensions together but it looks like none of the default extensions comands will work when ForceCode is activated:
```` 
Extension 'salesforce.salesforcedx-vscode-apex-debugger' failed to activate. Reason: dependency 'salesforce.salesforcedx-vscode-core' failed to activate.
Activating extension 'salesforce.salesforcedx-vscode-core' failed: command 'sfdx.force.apex.test.class.run.delegate' already exists.
Extension 'salesforce.salesforcedx-vscode-apex-debugger' failed to activate. Reason: dependency 'salesforce.salesforcedx-vscode-core' failed to activate.
````

Could it be your extension now overrides these default commands in a way?

**Comment by Codeneos** [comment]
Ah found it! You are registering the SFDX test class run commands; maybe it makes sense not to do that and instead let these be handled by the normal Salesforce extension (or make them conditional)?

Line 344 ``commands.ts``:
````js
    {
        commandName: 'sfdx.force.apex.test.class.run.delegate',
        hidden: true,
        command: function (context, selectedResource?) {
            return commandService.runCommand('ForceCode.apexTest', context, 'class');
        }
    },
    {
        commandName: 'sfdx.force.apex.test.method.run.delegate',
        hidden: true,
        command: function (context, selectedResource?) {
            return commandService.runCommand('ForceCode.apexTest', context, 'method');
        }
    },
````

**Comment by daishi4u** [comment]
Yes I do this to catch the run test commands because my extension relies on the salesforce apex extension for code completion and I didn't want to install all of the salesforce extensions, only the code completion ones.

**Comment by Codeneos** [comment]
Hmm, but to have full code completion also for SObjects you need to be able to refresh the sobject defs from time to time. That comand is not working when force code is enabled as it prevents loading of the core sf extension. Also both debuggers from sf depend on the core cli externsion and dont seem to work anymore together with forcecode.

Wouldn't it be better to provide these overrides as a seperate package? Or as a config setting instead? So that both can be used together?

**Comment by daishi4u** [comment]
I have a code completion refresh menu command that refreshes the sobject data so that it will work with the apex extension. As far as the incompatibility with the replay debugger I made this extension the way it is so I didn't have to use the other salesforce extensions. I might consider a configuration option in the future though. For now I will be updating the readme stating that this extension isn't compatible with salesforce extensions except the code completion ones.

**Comment by watro** [comment]
Sorry, to pitch in, but yes, this would be really helpful.  I also stumbled across this issue as I have both extensions installed.

**Comment by daishi4u** [comment]
ForceCode relies on 3 salesforce extensions, which are the code completion ones aka the language server extensions for lightning, visualforce, and apex

**Comment by Codeneos** [comment]
@watro : what I did is make a fork of the repo and removed the commands from commands.ts allowing you to both have forcecode and the salesforce provided debuggers active. You can easily do this yourself but if you want I can push my fork to github so you can just grab the updated VISX file from there.

**Comment by daishi4u** [comment]
Ok everyone, pushing up 3.5.7 now which fixes this issue. You will need to add "sfdxCompatibility": true to your force.json file in order to use the other extensions.

**Comment by Codeneos** [comment]
Thanks a lot!!

**Comment by daishi4u** [comment]
You're welcome. The next release will have this auto detected so it won't need to be manually set in the force.json file after that, this was just a quick fix for now.

**Comment by watro** [comment]
That's awesome!
