### ISSUE TITLE
once you log out, you cannot re-open the forcecode menu

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#31]
i am successfully logged in to my org, saving files, etc

force code menu, log out

force code menu....nothing happens

edit: i restarted vs code, logged into my other org, and then ForceCode tried to execute 860 tasks !!  i killed the process, deleted wsMembers.json and restarted again, no issues.

**Comment by daishi4u** [comment]
This is fixed it 3.5.6 now

**Comment by julesx** [comment]
confirmed
