### ISSUE TITLE
Problem deploying static resources with spaDist

### ISSUE THREAD

**Issue by rsalit1516** [daishi4u/ForceCode#32]
When I attempt to deploy a static resource I get the following error: Cannot read property 'replace' of undefined.

Are there any additional requirements in the force.json file that could make my project not work in this version of ForceCode?
{
    "checkForFileChanges": true,
    "autoRefresh": true,
    "showTestCoverage": true,
    "showTestLog": true,
    "showFilesOnOpen": true,
    "showFilesOnOpenMax": 3,
    "browser": "Google Chrome Canary",
    "pollTimeout": 1200,
    "debugOnly": true,
    "debugFilter": "USER_DEBUG|FATAL_ERROR",
    "apiVersion": "38.0",
    "deployOptions": {
        "checkOnly": false,
        "ignoreWarnings": true,
        "rollbackOnError": true,
        "testLevel": "runLocalTests",
        "verbose": true
    },
    "autoCompile": true,
    "url": "https://test.salesforce.com",
    "poll": 1500,
    "prefix": "",
    "spaDist": "build",
    "src": "src",
    "username": "sandbox username"
}

**Comment by daishi4u** [comment]
Are you using the proper folder and file naming convention that ForceCode requires? if you need an example then open a static resource from the org and you will see how everything needs to be named. I need to update the documentation for this...

**Comment by daishi4u** [comment]
Documentation has been updated in github for the static resource naming convention

**Comment by rsalit1516** [comment]
Thanks - much appreciated. I will check it out today!
<http://www.orthosensor.com> <http://www.orthosensor.com>
<http://www.facebook.com/orthosensor> <http://www.facebook.com/orthosensor>
<http://www.twitter.com/orthosensor> <http://www.twitter.com/orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+OrthoSensorInc>
<https://www.linkedin.com/company/1298958>
<https://www.linkedin.com/company/1298958>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor> <https://vimeo.com/orthosensor/>
<https://vimeo.com/orthosensor/> <https://vimeo.com/orthosensor/>
*Richard Salit*, Sr Software Developer
CEL 954-444-4479
TEL 954-577-7770, Ext 178
EMAIL richard.salit@orthosensor.com
1855 Griffin Road, Suite A-310, Dania Beach, FL 33004-2401
*Customer Service* *888-75-ORTHO (67846)*

**Comment by rsalit1516** [comment]
I seem to have the system set up correctly. I have a spaDist defined as
build which has my javascript files and then I also have a resource-bundles
directory with the resources (below them IQ_AppBundle.resource).

Can you see anything incorrect? Sorry to bother you but I'm trying to
finish a sprint by Monday. I had been running this for the past year up
until a few weeks ago.

<http://www.orthosensor.com> <http://www.orthosensor.com>
<http://www.facebook.com/orthosensor> <http://www.facebook.com/orthosensor>
<http://www.twitter.com/orthosensor> <http://www.twitter.com/orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+OrthoSensorInc>
<https://www.linkedin.com/company/1298958>
<https://www.linkedin.com/company/1298958>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor> <https://vimeo.com/orthosensor/>
<https://vimeo.com/orthosensor/> <https://vimeo.com/orthosensor/>
*Richard Salit*, Sr Software Developer
CEL 954-444-4479
TEL 954-577-7770, Ext 178
EMAIL richard.salit@orthosensor.com
1855 Griffin Road, Suite A-310, Dania Beach, FL 33004-2401
*Customer Service* *888-75-ORTHO (67846)*

**Comment by daishi4u** [comment]
Do you have the directories (spa and resource-bundles) in the root directory of your project? (Not in the src folder, but the same folder that force.json is in)

**Comment by rsalit1516** [comment]
Yes.
<http://www.orthosensor.com> <http://www.orthosensor.com>
<http://www.facebook.com/orthosensor> <http://www.facebook.com/orthosensor>
<http://www.twitter.com/orthosensor> <http://www.twitter.com/orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+OrthoSensorInc>
<https://www.linkedin.com/company/1298958>
<https://www.linkedin.com/company/1298958>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor> <https://vimeo.com/orthosensor/>
<https://vimeo.com/orthosensor/> <https://vimeo.com/orthosensor/>
*Richard Salit*, Sr Software Developer
CEL 954-444-4479
TEL 954-577-7770, Ext 178
EMAIL richard.salit@orthosensor.com
1855 Griffin Road, Suite A-310, Dania Beach, FL 33004-2401
*Customer Service* *888-75-ORTHO (67846)*

**Comment by rsalit1516** [comment]
Sorry, I've been working on some other projects and haven't had time to
perform additional testing. I ended up going back to the previous version
of ForceCode and then having to set @code back to version v1.24. Not the
best solution but will revisit when I have more development in that app.





<http://www.orthosensor.com> <http://www.orthosensor.com>
<http://www.facebook.com/orthosensor> <http://www.facebook.com/orthosensor>
<http://www.twitter.com/orthosensor> <http://www.twitter.com/orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+Orthosensor>
<https://plus.google.com/+OrthoSensorInc>
<https://www.linkedin.com/company/1298958>
<https://www.linkedin.com/company/1298958>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor>
<https://www.youtube.com/user/orthosensor> <https://vimeo.com/orthosensor/>
<https://vimeo.com/orthosensor/> <https://vimeo.com/orthosensor/>
*Richard Salit*, Sr Software Developer
CEL 954-444-4479
TEL 954-577-7770, Ext 178
EMAIL richard.salit@orthosensor.com
1855 Griffin Road, Suite A-310, Dania Beach, FL 33004-2401
*Customer Service* *888-75-ORTHO (67846)*
