### ISSUE TITLE
Retrieve Package / Metadata Option not appearing in the menu

### ISSUE THREAD

**Issue by watro** [daishi4u/ForceCode#34]
Hi, 

So, today I updated to version 3.5.10 and I don't have the Retrieve option in the menu.

There's a Retrieve a Salesforce file, but no option to "Get All Metadata" as there was before.

Was this option removed?

**Comment by daishi4u** [comment]
Read the readme, stuff changed a little. Since packages rely on metadata you will need to add the handleMetaFiles: true option to your force.json file

**Comment by watro** [comment]
Actually I did, but apparently did not understand that part.  Now, re reading makes sense.  Thanks!

**Comment by daishi4u** [comment]
You're welcome 😀
