### ISSUE TITLE
feature request : Aura Definition Bundle Override Warning

### ISSUE THREAD

**Issue by raghurankawat** [daishi4u/ForceCode#37]
It would be nice if this can show AuraBundle Override warning before saving file to server like it does for Apex Classes and VF.

**Comment by daishi4u** [comment]
I think this can be done, but it would only be able to warn before saving and not on startup like apex and vf does, but this sounds like it's what you're looking for anyways. I'll definitely look into it as it's a good idea!

**Comment by daishi4u** [comment]
This is implemented in 3.6.0

**Comment by raghurankawat** [comment]
Great... Thanks @daishi4u

**Comment by raghurankawat** [comment]
Hey @daishi4u 
Just tested this with 3.6.0 but it is not showing any warning and override changes on the server. Not sure what is wrong.
I updated one aura component file Test.cmp using developer console and then in vscode updated my local Test.cmp and hit save but it overrode on server without comparing. :(

**Comment by daishi4u** [comment]
how far apart did you wait before won't saved? There is a ten second leeway because of issues with time differences between metadata grabbed all at once vs the metadata grabbed when checking for a file change on save. So basically if you saved in the dev console then saved within ten seconds in forcecode then it will overwrite...

**Comment by raghurankawat** [comment]
@daishi4u Yes, I was saving it within 10 seconds. Just tested it after waiting 10 seconds or so and its working as desired.
I used to do development using https://www.aside.io/ which shows override warning for classes and Aura so happy to have same feature in ForceCode. Thanks
