### ISSUE TITLE
Running the contributed command:'ForceCode.openFileInOrg' failed.

### ISSUE THREAD

**Issue by hubwozniak** [daishi4u/ForceCode#39]
Running the contributed command:'ForceCode.openFileInOrg' failed.

**Comment by jmfierroh** [comment]
Hi, I've managed to reproduce this in v3.5.11,
Opening the "Log (Extension Host)" tab, reveals that the error is: `TypeError: Cannot read property 'fsPath' of undefined`
I'm guessing that the line that causes this is: [src/models/commands.ts line 338](https://github.com/daishi4u/ForceCode/blob/cc55f83f4caf9aaa9778a7e721bf93f4e48e6ba0/src/models/commands.ts#L338)

Hope that helps :)

**Comment by daishi4u** [comment]
Do both of you have the checkForFileChanges option in the force.json file set to false?

**Comment by jmfierroh** [comment]
Yeah, I've been forced to set checkForFileChanges to false, since there was a point in which the whole window froze with +1200 tasks. After setting it to false, (reloading,) then setting it back to true, though, _that_ issue hasn't come back.

> a little more details

Sure! What exactly do you need?

> anything special that you didn't mention

Uh... define special? :sweat_smile:

**Comment by daishi4u** [comment]
@jmfierroh 

> Sure! What exactly do you need?
If you wouldn't mind, could you give me all of the exact steps to reproduce. I know it's with an apex class open, but did you only have one open, two, ten? Did you open it right away, then try and open it in the org? Details like that could possibly help.

> Uh... define special? sweat_smile
I guess what I mean by special is anything other than simply opening the file in vscode, once ForceCode is loaded, and just trying to open in the org :)

**Comment by hubwozniak** [comment]
I do not know how, but bug has fixed itself in my case. I'm closing Issue.
