### ISSUE TITLE
Cannot read property 'tooling' of undefined

### ISSUE THREAD

**Issue by swapnilshrikhande** [daishi4u/ForceCode#4]
- Was able to authenticate
-  When trying to **Open Salesforce File** facing below error 
`
Cannot read property 'tooling' of undefined
`

**Comment by daishi4u** [comment]
So, you're sure that you were able to login successfully? Try and go to the menu and choose open org in browser. If it asks to login then you weren't logged in. Please let me know the outcome

**Comment by daishi4u** [comment]
Any update? If not, I'm going to close this issue, as it sounds like you weren't properly logged in.
