### ISSUE TITLE
Generic Oauth error on a brand installation

### ISSUE THREAD

**Issue by watro** [daishi4u/ForceCode#40]
Hi, 

Sorry to bother, but I am not sure how to debug this.

I am using a brand new computer, I installed node and npm, java 8, visual studio code v 1.25.1 and force code 3.5.11 and 3.5.10 (tried on both), browser Chrome.

I created a folder, clicked on Show force code menu and got the "You are not logged in, log in now" message.  I click on it and get redirected to the login form, after that, the page gets stuck (does not show anything) and I see a ForceCode: Executing 1 task on the bar on visual studio code.

I never get past this message, so no menu or anything like that.

If I refresh the page on the browser I get an oAuth generic error message.  Force code just stays eternally with the Executing 1 task message.

I tried changing the browser to safari, and it seems to trigger the login flow all the time.  It opens the browser and then closes it, and a new "You are not logged in, log in now" message appears every time.

I have forceCode working perfect with the same credentials on the old computer.

I'll be happy to debug it if someone can point me in the right direction.

**Comment by daishi4u** [comment]
Seems to happen to me once in a good while as well and I think it is an issue with the salesforce node package. You should be able to close the browser and vscode then open vscode again and try again

**Comment by watro** [comment]
Yeah, I tried closing, changing browsers and restarting but nothing seems to work this time.

I did find this on the output Log (windiow): 

[renderer1] [error] Cannot read property 'getWsMember' of undefined: TypeError: Cannot read property 'getWsMember' of undefined
    at /Users/watro/.vscode/extensions/brettwagner.forcecode-3.5.11/out/src/extension.js:36:27
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:97:917)
    at e.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:141)
    at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:87)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:779)
    at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:851)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:620)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:655:544
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:673
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:599
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:97:917)
    at u (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:159:721)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by daishi4u** [comment]
Are you changing a file before ForceCode is able to fully start? That's what it seems like with the error that you gave me.

**Comment by watro** [comment]
No, I'm not able to download the project, so changing a file if out of the quesiton.

**Comment by daishi4u** [comment]
Ok, well with what you gave me I'm going to push another version asap (3.5.13) let me know if this fixes it. I will comment on here once I have it pushed

**Comment by watro** [comment]
Great, I'll let you know as soon as I test it.  If there's any tip on how to debug it better I'll ber happy to help in any way I can.

**Comment by daishi4u** [comment]
Ok, 3.5.13 is up. Thanks, you've been a major help already!

**Comment by watro** [comment]
I get a "command 'ForceCode.showMenu' not found" message and nothing on the logs on 3.5.13 version

**Comment by daishi4u** [comment]
Do you have the Java setting configured right in the vscode settings?

**Comment by watro** [comment]
I think so, I had an error on version 3.5.11 because I had Java 10, so I
downloaded Java 8, added to the user settings like this:

"salesforcedx-vscode-apex.java.home": "/Library/Java/
JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home",

and the error disappeared.

But in all the tries, the further I went was opening the browser.  It get's
stuck there.

The only things installed on this computer are homebrew, git, visual studio
code, chrome, node, jdk 8 and 10.  Maybe I'm missing some other dependency?

**Comment by daishi4u** [comment]
Ah, so you're running Linux then? I develop ForceCode on Linux and have never had to add the setting, so it's strange that you would get this error. I'm running Ubuntu 18.04

**Comment by daishi4u** [comment]
Interesting. I've never tested with OSX so I'm not sure where to begin. I'll do some digging, but I might not have an answer tonight.

**Comment by watro** [comment]
Thank you very much for your help!

**Comment by daishi4u** [comment]
I fixed a major issue, referenced above, that is related to this so please let me know if 3.5.14 works for you.

**Comment by watro** [comment]
I just tried it, and it seems to work (downloading metadata from a big or which takes time), but had to do a change.

A couple of things I noticed.

Uninstalling 3.5.13 did not work from the UI, tried several times and I got an error where it was not finding the confirmation window.  Could uninstall it perfectly over the command line.

On version .14 initially it did not work.  Tried it a couple of times but I was still stuck on the oAuth and it was not reading it, so same error as before.  

The thing that got it working was to change the URL en in the force.json from test.salesforce.com to my sandbox cs93.salesforce.com and restart.

With that change, it did the oAuth dance flawlessly, it shows the menu and sidebar icon perfect.  Right now I'm doing a retrieve, will report back how that goes.  I did not try the URL change on the other versions, I can try to see if that works on .11 too if you want.

Thank you very much for your help!

**Comment by watro** [comment]
Ohh, I also changed the browser to Google Chrome, without the Canary, though I'm pretty sure it was the url that got it working.

**Comment by watro** [comment]
Retrieving metadata seems to be stuck.  It does not give an error message, but I tried retrieving all for 15 mins and nothing, so then I tried downloading Standard objects and was still stuck after about 10 mins.

**Comment by watro** [comment]
Ok, tried changing the URL back to test.salesforce.com and the retrieve package is definitely stuck.  Tried all options on the Retrieve and none of it worked.  

If I try to Open Salesforce File or Open Aura Bundle, it works flawlessly.

Nothing shows on the logs when doing the retrieve, so not sure how to debug it better.

**Comment by hwong103** [comment]
> Retrieving metadata seems to be stuck. It does not give an error message, but I tried retrieving all for 15 mins and nothing, so then I tried downloading Standard objects and was still stuck after about 10 mins.

This might be a separate bug, but I wanted to report that I'm seeing the same issue. `Retrieving package` appears in the Running Tasks section and never disappears

**Comment by daishi4u** [comment]
I'm going to close this. Any retrieve bug stuff can go into issue #42
