### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by jmfierroh** [daishi4u/ForceCode#41]
Hi,
I've downloaded forcecode-3.5.13.vsix to update my installation, when loading the window, ForceCode.showMenu cannot be found.

Opening the Developer Tools window, reveals that the plugin failed to load:
`[Extension Host] Activating extension 'BrettWagner.forcecode' failed: Cannot find module 'C:\Users\[UserName]\.vscode\extensions\brettwagner.forcecode-3.5.13\out\src\extension'`
`[Extension Host] Activating extension `BrettWagner.forcecode` failed:  Cannot find module 'C:\Users\[UserName]\.vscode\extensions\brettwagner.forcecode-3.5.13\out\src\extension`

![screenshot_2](https://user-images.githubusercontent.com/42169371/43839706-1031aa10-9b1f-11e8-83e8-c686de51fd1f.png)

Peeking around, I cloned and build the source, that ran perfectly. Using 7-zip to snoop inside the .vsix files, v3.5.11 has the missing out/src/extension (and therefore worked perfectly), where as v3.5.12 and v3.5.13 do not.

![image](https://user-images.githubusercontent.com/42169371/43838913-fd06038e-9b1c-11e8-9330-ccef856d0a64.png)

Huh, This seems related to issue #40

**Comment by daishi4u** [comment]
Great find! Thank you for this information. I won't be able to fix until later today, but it seems strange the vscode packager is leaving that out. I'll try reverting to an earlier version of the packager when I get home. Thanks again!

**Comment by daishi4u** [comment]
As an update, this is fixed in 3.5.14. Thanks once again for pointing this out!
