### ISSUE TITLE
Where should i define files for retreiving by name?

### ISSUE THREAD

**Issue by hubwozniak** [daishi4u/ForceCode#42]
Hi,
I am trying to retreive package by Name and i don't know where i should define the XML file. In scr folder and project folder doesn't work for me. Should i type only file Name or full path to the file ? 

Thank You for your help!

**Comment by daishi4u** [comment]
You should be defining it in the src folder. Does it give you an error when it is there?

**Comment by hubwozniak** [comment]
No, VS Code shows "Retrieving package" in RUNNING TASKS, but nothing heppens. I can give name of file that does not exist in src folder and it acts the same way.

**Comment by daishi4u** [comment]
Ok, I will need to do a lot of testing to get this to work so it may take a while.

**Comment by daishi4u** [comment]
This is fixed in v3.6.4

**Comment by hubwozniak** [comment]
Unfortunately it doesn't work for me. Retrieving package is stuck in running tasks when i try to retrieve package by name no matter how i define file.

**Comment by daishi4u** [comment]
If the retrieve by name pops up then that means forcecode couldn't find any packages using the query it does. What kind of package are you trying to retrieve? This will only pull unmanaged packages or ones that you create in the org.

**Comment by hubwozniak** [comment]
In scr folder i have file package1.xml, it contains:

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <version>42.0</version>
</Package>

The package.xml is exactly the same. When i go Menu->Retrieve Package->Retrieve by package.xml it works fine. But when i try Menu->Retrieve Package->Retrieve by Name and type package1 or package1.xml tasks are stuck in Running Tasks.

**Comment by daishi4u** [comment]
Ah, this isn't meant for package files, it's meant to download unmanaged packages from the org. The only way to download with a package.xml file is the way that you successfully did it 😀
