### ISSUE TITLE
error when saving Lightning JS

### ISSUE THREAD

**Issue by alexanderyhapcv** [daishi4u/ForceCode#45]
When trying to saving a lightning component js file I get this error...

> Cannot read property 'compareDates' of undefined

**Comment by daishi4u** [comment]
Has this error only been with lightning javascript or have you received it with other component parts? (css or the component itself) Have you tried exiting out of vscode and starting it again and then saving? Was this an existing javascript file or a new one?

**Comment by alexanderyhapcv** [comment]
yes, I only get this error when trying to save lightning javascript files & I do receive the error on other components. I've also tried restarting vs code and the error keeps occurring.

**Comment by alexanderyhapcv** [comment]
how can I get more information to help you? is there a log I can pull from vs code?

**Comment by daishi4u** [comment]
No I don't have a log system in place, but I was able to reproduce it today so I'll get it fixed when I can hopefully tonight. Thanks

**Comment by daishi4u** [comment]
This is fixed in v3.6.2

**Comment by alexanderyhapcv** [comment]
🙌THANKS FOR THE FIX!!!
