### ISSUE TITLE
Errors getting "stuck" in problems pane

### ISSUE THREAD

**Issue by daishi4u** [daishi4u/ForceCode#46]
When saving an apex class that has errors in it, sometimes the errors will get "stuck" in the problems pane on 3.6.2. and vscode 1.26.0

Proposed solution: reset diagnostic collection each time on save, look into what changed in the diagnostic collection in the vscode api with the 1.26.0 release and see if there's a reset function.

**Comment by JorneVL** [comment]
Had the same issue with 3.6.1. If I downgrade to 3.5.14, the problem doesn't happen.

**Comment by daishi4u** [comment]
Yep, this is a vscode issue and I created an issue on their github here https://github.com/Microsoft/vscode/issues/56528

**Comment by JorneVL** [comment]
For me this is fixed with the 1.26.1 release. Can you confirm?

**Comment by daishi4u** [comment]
Yeah that issue came from the vscode upgrade as well, but I fixed it in v3.6.3. All should be good to go now
