### ISSUE TITLE
Notifications vs Problems

### ISSUE THREAD

**Issue by JorneVL** [daishi4u/ForceCode#47]
Hello,

Sometimes when I save classes with Forcecode I receive errors in Notifications and not in Problems or both.
For me Notifications should be used for problems with Session token or similar with that.
Problems should be used when there is a Syntax error or a problem when saving a file.

**The next example gives the error in Notification and Problem**
When you solve this issue it stays in Notifications. This should disappear as well, or maybe easier, never show in the Notifications
`Account accountInstance = new Account();
if(account.Date_Field__c = null)`

**Problem that is only in Notification**
Time out when saving a class
Dependent class is invalid
When you save the same class two times, sometimes you receive a Notification like 'This container member belongs to a container that currently has an unfinished save request with deploymentId...'

These Notifications are not easy to link with a file. So I prefer to see these in the Problem Panel, if you need to add a Line Number, maybe you can take the first line.

What do you think about this?

And a last question, when you have a difference and you want to look into it, how can you overwrite this without a extra save? Is it possible to only save some sections, like a merge in GIT?

Thank you for your work in ForceCode.

**Comment by daishi4u** [comment]
This issue should be resolved it v3.6.3. Check it out and let me know what you think. If all is well you can just go ahead and close this issue. Thanks

**Comment by JorneVL** [comment]
Why do you always add a Notification? If a user save a class and it fails, there will be a issue in the Problem panel. If you prefer to use the Notification, no problem.
Thank you.

**Comment by daishi4u** [comment]
True, I can change it up to not do this.

**Comment by daishi4u** [comment]
Notifications removed in 3.7.0
