### ISSUE TITLE
Cannot read property 'compareDates' of undefined error when editing Lightning Event

### ISSUE THREAD

**Issue by Pflaumen** [daishi4u/ForceCode#48]
VSCode: Version 1.26.1 (1.26.1)
ForceCode: 3.6.5

When attempting to edit a lightning event, I receive the error "Cannot read property 'compareDates' of undefined". I don't receive the error when editing other items (lightning components, apex classes).

I've also tried 3.6.4 and 3.6.6 and receive the error on both of those versions as well.

**Comment by daishi4u** [comment]
This is fixed in 3.7.0
