### ISSUE TITLE
'Retrieve Package' is not work on VSCode1.26

### ISSUE THREAD

**Issue by sytstakuya** [daishi4u/ForceCode#49]
'Retrieve Package' is not work on VSCode1.26.
Its option is not displayed in forcemenu.

**Comment by raghurankawat** [comment]
For me its showing 'Retrieve Package' with VSCode 1.26.1....maybe you have "handleMetaFiles": false, in force.json

**Comment by daishi4u** [comment]
@sytstakuya,  raghurankawat is right, you have handleMetaFiles set to false. For ForceCode 3.7.0 and up you won't need to worry about that option as it no longer exists and Retrieve Package is always available.
