### ISSUE TITLE
command 'ForceCode.showMenu' not found

### ISSUE THREAD

**Issue by dariomapelli** [daishi4u/ForceCode#5]
Hi,
no functionality works now.
I'm using your 3.2.9 build and Visual Studio Code 1.25.0, running on MacOS.
Same problems occurs with Visual Studio Code 1.24.1.
I haven't tried other versions.
I also tried to install Apex and Visualforce extensions by JohnAaronNelson first, same problems.
Thanks

**Comment by daishi4u** [comment]
Did you install Java 8?

**Comment by dariomapelliTelnext** [comment]
Thanks for the reply. I'm using Java 1.8.0_112

**Comment by dariomapelliTelnext** [comment]
yea, now it works. Thanks!

**Comment by jutxle** [comment]
No luck on Win 10 with either 3.3.0 or 3.3.1 and VSCode 1.25, still seeing the same error.

**Comment by julesx** [comment]
@jutxle i would uninstall all related packages (including salesforce-dx official extensions) and try again. 3.3.1 seems pretty solid so far
