### ISSUE TITLE
Refresh File from server ovveride package.xml

### ISSUE THREAD

**Issue by mohametso** [daishi4u/ForceCode#52]
When i click on refresh file from server, the package.xml body is always ovverided by the component that i try to retrieve.

**Comment by rock-pile** [comment]
Same, fetched a file from my dev org and it overwrote the existing package.xml, that was unexpected and shouldnt really happen.

**Comment by daishi4u** [comment]
I will add an option in the next release in force.json for overwriting the package file. sorry for the inconvenience.

**Comment by daishi4u** [comment]
This is solved in 3.7.1. A new force.json option was added called overwritePackageXML. If you leave it out of your force.json or it's set to false then it won't overwrite the package.xml. If set to true then it will overwrite

**Comment by mohametso** [comment]
It's working fine now many thanks for your job really appreciate 👍

**Comment by daishi4u** [comment]
Glad to hear that 😀 You're welcome, working on this is my current hobby and it's been fun 😀😀
