### ISSUE TITLE
No option to run Unit Tests?

### ISSUE THREAD

**Issue by rock-pile** [daishi4u/ForceCode#53]
When looking for 'Menu: >ForceCode Menu... Run Unit Tests'  it does not exist.

**Comment by rock-pile** [comment]
Also should mention, that Ctrl - Shift - T does not work to run Unit Test.  When I checked the mapping it was mapped to open a previously closed file.

**Comment by daishi4u** [comment]
Hover over an @isTest or a testMethod keyword and you'll see the option to run
