### ISSUE TITLE
Error when saving a Class

### ISSUE THREAD

**Issue by JorneVL** [daishi4u/ForceCode#56]
I have received a error when I try to compile a class.
I have added the log of error, see gist.
After this I can't save any more. If I compile there is a quick message 1 task and then it disappears after that. No confirmation that the Compile is completed.
https://gist.github.com/JorneVL/fc44cb5d966193b5f5806508f7feba06

**Comment by daishi4u** [comment]
Okay this will be fixed in the next release

**Comment by JorneVL** [comment]
I have installed 3.7.1 and still have this issue.
I think this appears on the next level
https://github.com/daishi4u/ForceCode/blob/master/src/extension.ts#L37
`if (isResource.index) {`
Shouldn't this be converted to the next if?
`if (isResource != undefined && isResource.index) {`

I don't know if this is the full solution...

**Comment by daishi4u** [comment]
I haven't pushed a new release since you reported this issue lol. I have it fixed already but I'm not done with the new release yet, it's a big one

**Comment by daishi4u** [comment]
It will be fixed in version 3.8.0

**Comment by daishi4u** [comment]
This is now fixed, version 3.8.0 is uploaded. Please read the README as a LOT has changed including the project structure.
