### ISSUE TITLE
Where do I find System.debug() logs?

### ISSUE THREAD

**Issue by FBosler** [daishi4u/ForceCode#58]
I can not seem to find the System.debug() evaluations that I use on test classes to check intermediate results.

I did change the debugFilter to "DEBUG|USER_DEBUG|FATAL_ERROR" and showTestLog is set to True.

Any help would be appreciated

**Comment by daishi4u** [comment]
If there are logs after running a test class then they will open in a new editor after the test is run. if there is nothing to print out then it won't open. You can also access the last ten logs by accessing the get logs option in the menu. If you want to see all output from the log without a filter then set the option debugOnly in force.json to false.
