### ISSUE TITLE
Code Coverage After Test (for Trigger)

### ISSUE THREAD

**Issue by FBosler** [daishi4u/ForceCode#59]
Maybe I am doing something wrong, but I can seem to find any code coverage results.

I do get results, like this:

=== Test Results
TEST NAME                              OUTCOME  MESSAGE  RUNTIME (MS)
─────────────────────────────────────  ───────  ───────  ────────────
checkRecursiveTest.checkRecursiveTest  Pass              37

=== Test Summary
NAME                 VALUE
───────────────────  ──────────────────────────────────────────
Outcome              Passed
Tests Ran            1
Passing              1
Failing              0
Skipped              0
Pass Rate            100%
Fail Rate            0%
Test Start Time      Aug 27, 2018 9:57 AM
Test Execution Time  37 ms
Test Total Time      39 ms
Command Time         9367 ms
Hostname             xxx
Org Id               xxx
Username             salesforce-dev@thehomelike.com.fabiansbox

sfdx force:apex:test:run --tests checkRecursiveTest --resultformat human --synchronous --loglevel error ended with exit code 0

and I can successfully deploy the classes/triggers and test them during deployment. But its always a bit of a gamble :)

Is there a way to see, which parts of my Apex triggers are actually covered/not covered?

**Comment by daishi4u** [comment]
Is the class that you're trying to test for in the code coverage view? If so, what category is it under? Does it show coverage in the org?

**Comment by daishi4u** [comment]
Ah, I see now, this is because you're running the salesforce's extensions' test, it's not being run through ForceCode...Going to close this. You need to hover over @isTest or testMethod to get the forcecode test command to pop up...
