### ISSUE TITLE
SFDX and ForceCode

### ISSUE THREAD

**Issue by mohametso** [daishi4u/ForceCode#60]
Hi, 
sorry may be it's not a defect but i'm trying to develop into my scratch code directly with forceCode and after use SFDX command force other deployment option, but i can't log into my scratch org, is it possible ? many thanks for your help :)

**Comment by daishi4u** [comment]
I have honestly never used the new way (SFDX and scratch orgs) of developing for Salesforce so I'm not sure if it is or not. The Salesforce extensions provide ways to integrate vscode with scratch orgs, I do know that. Maybe someone else can chime in and answer.

**Comment by dmgerow** [comment]
If you are using scratch orgs there probably isn’t much use for this extension - why not just use DX and the vscode DX plug-ins? This power of this extension comes from being able to dev in other environments. 

If you are working with scratch orgs and want  to still use the metadata api you can with the sfdx mdapi commands. 

What ForceCode features are you looking to use with scratch orgs? 

If you do want to use this with a scratch .org you theoretically can but you’ll need to use the cli in DX to get the username and password first.

**Comment by daishi4u** [comment]
Thanks @dmgerow!
