### ISSUE TITLE
feature request: more graceful timeout

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#62]
if i leave my vs code open overnight, my auth to my org times out.

when i come back in the morning and try to (for example) save a class to my org, the status bar changes for half a second showing that it is attempting to save the file, but then nothing happens and status bar reverts to normal.

**Comment by daishi4u** [comment]
This is fixed in my next release. I'm almost done with it, just a few more issues to work through, it's a big release so far.

**Comment by daishi4u** [comment]
This is now fixed, version 3.8.0 is uploaded. Please read the README as a LOT has changed including the project structure.
