### ISSUE TITLE
Retrieve Errors INVALID_TYPE: Unknown type:null

### ISSUE THREAD

**Issue by Pflaumen** [daishi4u/ForceCode#65]
In both 3.7.1 and 3.8.0 I am receiving the following error when trying to refresh lightning components (including helpers/controllers/css) from the server.

Retrieve Errors INVALID_TYPE: Unknown type:null

Any idea what could be causing it? I have no issues with Apex classes, but lightning events get the same error.

More info: The error occurs when going to ForceCode: Refresh from server. Going through the ForceCode Menu and opening the file (even if it is already open) does not receive an error.

**Comment by daishi4u** [comment]
I actually haven't implemented a refresh for lightning components yet, but I can definitely work on doing it. I may only be able to refresh the entire bundle though... not individual pieces

**Comment by Pflaumen** [comment]
Refreshing the entire bundle would be fine!

**Comment by daishi4u** [comment]
This is fixed in 3.8.1
