### ISSUE TITLE
force.json being overwritten on vscode startup

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#66]
i have a custom setting for the `src` attribute

everytime i start vs code it is reset to default `"src": "src"`

i am attempting to create a class and it complains about the "classes" directory not existing at a certain path because my src attribute is incorrect.

also when the create class fails because of this error, the running task is stuck

**Comment by daishi4u** [comment]
Did you read the readme? Go through it and look at the new options that are available... Don't use the src option anymore, it's only for saving the last open org info.
