### ISSUE TITLE
lightning component compile does not get new helper

### ISSUE THREAD

**Issue by KevinGossentCap** [daishi4u/ForceCode#68]
When you created a component that did not have a helper at first.
If you then create a helper file from VSCode, it will not be sent to the ORG when compiling.

**Comment by daishi4u** [comment]
Do you by chance have any syntax errors in your helper you created? Try to create a helper in the dev console then just select all from the forcecode helper file and paste it in and try saving. The reason I ask is I had this type of issue with apex classes where you'd get no notification of it not being saved on the server if you had syntax errors. If you could provide that info it would greatly narrow down the issue, thanks.

**Comment by daishi4u** [comment]
This is fixed in 3.8.2
