### ISSUE TITLE
lightning component Controller.Js override warning

### ISSUE THREAD

**Issue by raghurankawat** [daishi4u/ForceCode#69]
I am facing an issue while saving Controller.Js file. It is saving file correctly on server only on first save and after that each time I modify same controller.js then it is giving me warning like "Someone has changed this file!" Diff and Override! 

Although is saving helper , cmp and other files without any issue but not working with controller.js.

**Comment by daishi4u** [comment]
Did you create the controller in forcecode or in the dev console? Try clicking override once and see if it does it again after that. If not then I know where the problem is.

**Comment by raghurankawat** [comment]
I created controller.js in dev console and retrieved that using package.xml. Also tried clicking override button and then tried to save but it keeps on asking to override every time.

I tried this with different sandbox but it is giving save warning.It does not give warning on first save but after that keeps on showing override popup.

**Comment by daishi4u** [comment]
This is fixed in 3.8.2
