### ISSUE TITLE
Running Tasks Window does not show any task

### ISSUE THREAD

**Issue by amitkumarj1979** [daishi4u/ForceCode#70]
Even though tasks are running Running Tasks Window does not show any task

**Comment by daishi4u** [comment]
Screenshot??

**Comment by amitkumarj1979** [comment]
Attached is the screenshot. Statusbar shows 1 task running (Retrieve task is running), but the window is blank
![blankrunningtask](https://user-images.githubusercontent.com/16682228/45401072-d0db7300-b603-11e8-9453-13b3e3c1df75.jpg)

**Comment by daishi4u** [comment]
That's not where forcecode shows its running tasks. Forcecode displays its running tasks in the ForceCode view. Click the cloud on the left and then try running something again and you will see...or better yet just click on the status bar item that says "Forcecode executing ...tasks" and it will reveal it and show you what it's doing.

**Comment by amitkumarj1979** [comment]
Got it thanks, i was looking at the wrong window.
