### ISSUE TITLE
Should show in status which user and SB the extension is currently logged in 

### ISSUE THREAD

**Issue by amitkumarj1979** [daishi4u/ForceCode#73]
Should show in status which user and SB the extension is currently logged in

**Comment by daishi4u** [comment]
This is in the switch user they. Read the readme before opening more issues

**Comment by amitkumarj1979** [comment]
this is my feedback, u can always mark them as a feature and keep in your list.

**Comment by daishi4u** [comment]
This particular issue I'm not going back on, but I have added explorer menu context options to save and retrieve almost any type now, just so you know with the other issues that you opened.
