### ISSUE TITLE
Standard Objects like Account/Contact are not pulled

### ISSUE THREAD

**Issue by npathuri0531** [daishi4u/ForceCode#76]
ForceCode extension doesn't seem to be pulling standard objects like Account/Contact/Case etc..Ideally they should show under objects folder but I don't see them.Also It doesn't seem to pull "WebLinks" for standard objects.

**Comment by daishi4u** [comment]
Please refer to this link https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm

Standard objects can't all be pulled at once unless each one is explicitly listed in a package xml...

**Comment by npathuri0531** [comment]
@daishi4u Hi Brett, You are right and I knew this. I used Retrieve Package/Metadata command and system retrieved entire meta data except the standard objects. My expectation was to pull everything. May be behind the scenes, can it also pull all standard objects and their weblinks?

Chait

**Comment by npathuri0531** [comment]
@daishi4u The custom object retrieves/deploys work perfectly fine. I only see issues with standard one's..These are really useful and will add lot of value. For the standard object retrieval, do you see any issues with fixing them? Thanks for all the great work you do!

**Comment by daishi4u** [comment]
Got this working, it will be in the next release!

**Comment by npathuri0531** [comment]
Thanks Brett. I am excited to see this in action.. can you please notify me when it is ready so I can test.. thanks

**Comment by daishi4u** [comment]
Of course. When I release a new version, I always post on the issues that I've addressed in the release and then close the issue.

**Comment by daishi4u** [comment]
This is now fixed in 3.8.4
