### ISSUE TITLE
feature request : option to create New code components directly from ForceCode

### ISSUE THREAD

**Issue by raghurankawat** [daishi4u/ForceCode#77]
Hi 
Can we have an options to directly create New AuraBundle, VF page and VF component from ForceCode menu for legacy salesforce. Currently we can create Apex class which is very helpful and having an option to create other code metadata would be great.

Thanks

**Comment by dmgerow** [comment]
You should be able to do this with the DX CLI and it will save with ForceCode

**Comment by daishi4u** [comment]
Yes this is true, and if you want apex code smartness then you need the cli anyways so you'll already have this feature. We should take a vote on removing the create class feature from forcecode too I think because I designed my version to work alongside the salesforce extensions...

**Comment by raghurankawat** [comment]
@daishi4u Yes, I know we can use CLI with sfdx to create different kind of metadata but I was asking it for legacy salesforce system where Dev hub is not enabled. Currently we can create apex class without DX and its working great so having an option to create other metadata would be great addition for legacy org.

**Comment by dmgerow** [comment]
@raghurankawat You don't need to authenticate to a devhub to use the CLI in the context of ForceCode.

**Comment by daishi4u** [comment]
@dmgerow That's what I thought, but I hadn't had time to verify. Thank you for that. Also, as a side not, if you have the cli installed with the apex extension and you create a new class manually then if you type class in the new blank file then there's a snippet that will do the rest for you as well.
