### ISSUE TITLE
Cannot use extension behind network proxy

### ISSUE THREAD

**Issue by VinickGold** [daishi4u/ForceCode#79]
Seems when we are behind a network proxy the extension is not able to listen on localhost:1717 to retrieve the token after we provide login and password into browser. 

![image](https://user-images.githubusercontent.com/8043172/45313489-6e9c4880-b505-11e8-8ace-8c232f528aae.png)

For this reason we can't use the extension if we are in the office inside the company network. Previously when username/password were in force.json, the extension worked just setting up HTTP_PROXY and HTTPS_PROXY environment variables as defined [Here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm) and setting "http.proxyStrictSSL":true in vscode settings.

**Comment by daishi4u** [comment]
Have you tried doing what is listed here https://salesforce.stackexchange.com/questions/194719/salesforce-dx-proxy-issues

**Comment by VinickGold** [comment]
Hi @daishi4u, i will try it again with all configs described. We did most of those configs but not all at the same time i think. After test i will post here the result.

**Comment by VinickGold** [comment]
Hi, thanks @daishi4u 

It worked after execute all the configurations and remove the special characters from my password due npm bad encoding.

**Comment by daishi4u** [comment]
Glad you got it working! Enjoy 😀
