### ISSUE TITLE
feature request for running tasks

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#8]
feature request

give running tasks its own side-tab section, like explorer, search, debug, extensions, etc.

use the badge functionality to display that something is going on at a glance.

currently, the way running tasks is embedded into the standard file explorer is not very useful, considering i am on often on other tabs, or have the tasks section collapsed, or even the entire sidebar collapsed.  if badging on the sidebar was used, it would be very easy to see at a glance that something is going on.

**Comment by daishi4u** [comment]
At this moment, I don't believe there's a way to do this with vscode.

**Comment by julesx** [comment]
There is, I have a Bookmarks extension that does this

**Comment by daishi4u** [comment]
What's the name of the bookmark extension so I can see if I can find some code on how to implement it?

**Comment by julesx** [comment]
nice! the action bar item is a definite improvement, badging will tie it all together.

**Comment by julesx** [comment]
the SVN extension has some control over badging.  the badge count represents the number of changed files, so there is at least some level of control over badging.
