### ISSUE TITLE
After upgraded to 3.8.4 ForceCode is freezing VSCode attempting to run over 1000+ tasks

### ISSUE THREAD

**Issue by rock-pile** [daishi4u/ForceCode#80]
I am working on a very large lightning project, 1000+ apex classes, 300+ lightning components.

After upgrading to 3.8.4, when I open my project, or even set it up new again ForceCode immediately starts running 'tasks'.

The status bar says 'ForceCode: Executing 1082 Tasks'  ..
VS Code then freezes up then after awhile I get the message to 'Wait or Reopen or Close' VSCode.. I've let it run for hours, it never finishes.  I need to force close it.  When I reopen ForceCode the process starts over again.

I've deleted my project folder, set it up again from scratch, same thing.

**Comment by daishi4u** [comment]
Set the option checkForFileChanges to false in your force.json, it won't check on startup again and you shouldn't have this problem.

**Comment by daishi4u** [comment]
This is fixed in v3.8.7. There is a new option (maxFileChangeNotifications) which is set to a default of 15. Forcecode will only show a max of that number of file change notifications on startup.
