### ISSUE TITLE
Feature Request: Making it easier to identify which org/sandbox a file is from

### ISSUE THREAD

**Issue by hwong103** [daishi4u/ForceCode#81]
Now that it's super easy to switch between sandboxes (awesome work btw!) I'm finding that it's really easy to open the wrong file for the the org that I'm currently logged into. 

For example when opening a class via the Quick Open (Ctrl+P) panel and I start typing the class name I can have 3 instances of the same class may come up and the first one in the list may not be the file that sits in the org that I'm logged into.

I guess what I'm wondering is: 

- if there's a way to make this a little clearer/easier to have the files come up first for the org you're logged into in the Quick Open panel

- Once files are already open, be able to clearly identify the files on screen are from different orgs (maybe by different coloured clouds?)

**Comment by daishi4u** [comment]
I can't change the way that the quick open menu acts, but I'll try and think of something to use as an indicator. I like your idea of the different colored clouds and I'll look into changing the icon color for just the files in the org, not sure if it can be done or not, but we'll see 😀

**Comment by daishi4u** [comment]
I will leave this open, but I will tell you about a handy feature that vscode has which is called breadcrumbs. If you go to the view menu, then toggle breadcrumbs then you'll see what I'm talking about. this way if you have a file open in your org and want to open another one from the same org then you can use that. I know it's about like the file explorer, but it help to remind you what org you're working in too from the path.

**Comment by hwong103** [comment]
@daishi4u thanks for the suggestion! I'll give that extension a try :)

**Comment by daishi4u** [comment]
I've added a new section in the code coverage view called 'Open files not in src' which will tell you which open files aren't in the current org's src folder. Due to the way vscode reports open files, however, it won't properly populate on start until you switch to that open file. Let me know what you think.

**Comment by hwong103** [comment]
@daishi4u thanks for putting that in. After using it quite a bit and switching between orgs I have to be honest I find using the Breadcrumb extension a lot more helpful in knowing if I've opened the file in the wrong org especially since it's so visual and isn't dependent on being on the Left sidebar (Forcecode specific). 

I think what I struggle with is actually opening/selecting the right file from the Quick Open menu (I know you mentioned you have no control over that) so I'm not sure if there's any real fix for that. 

Thanks for having a look at this anyway :D
