### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by damo24** [daishi4u/ForceCode#87]
I'm trying to install forcecode forcecode-3.8.x.vsix using vsix file and I'm having this error message.
Using Visual Studio Code 1.27.2 in OS X 10.13

**Comment by daishi4u** [comment]
You need to open vscode then go to the extensions view. Click the drop-down menu then select install from vsix

**Comment by damo24** [comment]
Yes, this are the steps I have followed before the error has ocurred.

**Comment by damo24** [comment]
Apparently the vsix files was corrupted.
I've dowloaded forcecode-3.8.5.vsix and it works.
Thanks daishi4u!

**Comment by daishi4u** [comment]
Great news! You're welcome :)
