### ISSUE TITLE
FR: Add ability to only deploy files defined in package.xml

### ISSUE THREAD

**Issue by fitzman49** [daishi4u/ForceCode#88]
**Is your feature request related to a problem? Please describe.**
Not a problem but more of a nice to have.

I've tried to use the Deploy Package option in the ForceCode menu to deploy the components defined in my package.xml but cannot due to the sheer size of code we have for our org.  Every time I try to deploy I get the following error "Maximum size of request reached. Maximum size of request is 52428800 bytes." due to the plugin zipping up all project files into a single executable and deploying that.

**Describe the solution you'd like**
Create an option that will only zip up the files we have defined in the package.xml (similar to what the Force.com IDE for Eclipse does) and only deploy those files along with the package.xml.  This will greatly reduce the deploy time and and network traffic to Salesforce.

**Describe alternatives you've considered**
I've been using save to server on each individual file.  While this does work, it can become tedious with lots of file changes and doesn't allow me to test that I've correctly defined package.xml member names in a sandbox before I push up to production environments.

**Additional context**
See attached screenshot for error message.
![forcecode_error](https://user-images.githubusercontent.com/5747425/45553155-16b15a80-b801-11e8-820b-d86943eb53c8.PNG)

**Comment by daishi4u** [comment]
I have actually been thinking about doing this for a while because I think it's a pain too. I can't give you an ETA for implementation, but I will definitely add this ability in a future release. (It won't be the next one because that one's already ready to go, just need to update a few things and build, but possibly the release after that (v3.8.6 or so))

**Comment by fitzman49** [comment]
No need for an exact date on implementation but I'm glad you've already started thinking about it!  We have a workaround like I said in the original request so it's not like I need it ASAP.  I'm just trying to think of things I used to to Force.com IDE that were super useful and this was one piece of functionality that is missing in ForceCode today.

Appreciate all the hard work you're doing and I'll keep an eye on this ticket if you need anything from me in regards to testing, etc.

**Comment by daishi4u** [comment]
So, I decided to implement this a little sooner than I mentioned earlier. This is now in v3.8.5. It does still deploy destructiveChanges.xml, destructiveChangesPre.xml, and destructiveChangesPost.xml files as well.
