### ISSUE TITLE
code coverage confusion

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#9]
it is hard to tell if code coverage is toggled on or off.  the icon should change, or something.

to compound the issue, it doesn't seem like there's any indicator that there is 0% code coverage for a file.  

when looking at a file that has no code coverage, and code coverage is toggled on, there is no indication that there is simply no coverage.  it makes it sort of hard to tell if something is broken or not.

on top of that, i am looking in the ApexCoverage file that is generated, and I see a file that is 57% covered.  yet in vs code there is no inline code coverage.  however I can open up a different file that is 90% covered and it works fine.  is there some sort of cutoff point?

update: i see now that there is two different options to retrieve code coverage, and only one of them enables the inline code coverage.  i have a different vscode workspace folder with some additional classes that are outside of my `"src": "sfdc"` config.  is there a way to provide more than one src folder?

**Comment by daishi4u** [comment]
I hope the 3.5.x updates help to clear this confusion a little bit :)

**Comment by julesx** [comment]
code coverage just doesn't seem to be working at all for me now.

i see now that there is only one option in the forcecode menu for retrieving code coverage, which does work, but opening up files that have coverage does not show anything.  the toggle button is also still unchanged, i can't tell if it's on or off.

**Comment by daishi4u** [comment]
Ok, just to clarify, for the next release I'm going to separate them into Sufficient/Insufficient coverage sections instead of covered/uncovered. The Sufficient coverage will only include files covered with >= 75%, all others will show in the other folder and percentages will show even if it has 0 percent. Should tidy things up a bit.

**Comment by daishi4u** [comment]
See if v3.5.3 makes things a little better for you :)

**Comment by julesx** [comment]
i see Insufficient Coverage and Test Classes, which is nice, but no Sufficient section.

**Comment by daishi4u** [comment]
The next release will refresh the test coverage data upon opening or refreshing a file.

**Comment by julesx** [comment]
When you say “opening a file”, do you mean opening it directly from the org via force code menu, or just opening a local copy?

**Comment by daishi4u** [comment]
I mean by the forcecode menu

**Comment by julesx** [comment]
Not so useful for me personally. I basically never do that. Possible to do this when opening a local file?

**Comment by daishi4u** [comment]
If the file is there before you open vscode then it should as long as it exists in the org...obviously 😀 but I wouldn't bother with refreshing for each file on open of the file, as you could kiss your api limits bye pretty quick... haha. I can think of other ways I suppose. Give me a detailed scenario when you're opening local files that aren't(?) in the project already that you make each time you make a new one so I know exactly what you mean please (if I didn't cover it already)

**Comment by julesx** [comment]
issue with 3.5.4:  when i double click a file from the "Insufficient Coverage" listing, i see the inline code coverage. great.

however if i open that same file from the regular file explorer, i do not see the inline code coverage.

is this by design?

**Comment by daishi4u** [comment]
It should display it both times, so it's interesting that it doesn't for you as it does for me.

**Comment by daishi4u** [comment]
I think I know exactly what's causing that issue. I will change some code later tonight and see what I can come up with.

**Comment by daishi4u** [comment]
Check out 3.5.5 and let me know what you think about the coverage changes. If you have questions about the new section, refer to the readme in the changelog.

**Comment by julesx** [comment]
I am still able to open the same file twice, once from ForceCode tab and once from file explorer or ctrl-p filename

inline coverage still only shown when opened from the ForceCode tab

**Comment by daishi4u** [comment]
Interesting. I think that does help though, as I know where to start looking to solve the problem; however, I have never faced this issue so it's strange that you're the only one having it so far.

**Comment by daishi4u** [comment]
Is this still an issue for you with the newer versions?

**Comment by julesx** [comment]
i am still able to open the same file from both the forcecode and explorer tabs

i am only shown coverage when opening it from the forcecode tab

![image](https://user-images.githubusercontent.com/3010047/44151312-3a09b17e-a070-11e8-9b88-086a412fc4ef.png)

when i use the ctrl-p shortcut, this same file displays twice.  the first instance is under the "classes" folder which is directly added to my vs code workspace.  the second instance is a few folders down from my project root folder, also added directly to my vs code workspace.

**Comment by daishi4u** [comment]
OK, I think I see what may be happening here. In your force.json, what do you have your src option set to? Only folders under the src folder will show coverage.

**Comment by julesx** [comment]
`"src": "code\\aem\\sfdc"`

code directory is underneath project root
sfdc directory contains the classes directory

opening the file in question from this tree does not show coverage

**Comment by daishi4u** [comment]
Have you tried removing the double backslashes? With the src option you shouldn't need them.

**Comment by julesx** [comment]
if i remove the double slashes i get red squigglies telling me i have invalid escape characters in my json string.  i removed them anyways and tried the following (3.6.2)

clicking the "here" on a test method tooltip successfully runs the test

clicking the "here" on a test class throws an error
![image](https://user-images.githubusercontent.com/3010047/44211917-13f71300-a138-11e8-9bd0-1865302d8be5.png)

either way the file remains under "no coverage data" even though i have successfully run the test methods individually

**Comment by daishi4u** [comment]
I've been trying to recreate this, but can't seem to so far. I'm trying here :)

**Comment by julesx** [comment]
anything i can do to assist?

going over this thread i feel like i've provided everything that should be required to repro it.

hmm.

**Comment by FBosler** [comment]
I am not seeing any code coverage for my Apex Trigger, is there a way to resolve the issue?

**Comment by daishi4u** [comment]
See if v3.8.0 clears this up

**Comment by george-beatty** [comment]
I was having similar issues, whereby I would run the test from the 'here' link on the test method in VS Code, but the coverage in the APEX class did not update. This appears to be fixed in 3.8.6
The correct coverage is also reported in the code coverage section of the sidebar. In my case, the class had no coverage and the file was listed under 'No Coverage Data'. I created a test, ran it from VS Code, and the file now shows coverage and appears in the 'Insufficient Coverage' list, with 8% coverage.
Happy days, thanks.
