### ISSUE TITLE
access token not prompting for refresh with 3.8.4

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#90]
**Describe the bug**
access token refresh doesn't seem to be working properly. i am presented with an error toast when attempting to save a file after vs code has been idling for a significant period of time.

**To Reproduce**
1. leave vs code open overnight
2. attempt to save sf file
3. attempt to save sf file again

**Expected behavior**
token should be automatically refreshed

**Screenshots**
following errors appears:
![image](https://user-images.githubusercontent.com/3010047/45624825-65593180-ba59-11e8-89ed-44128261b97f.png)
![image](https://user-images.githubusercontent.com/3010047/45624879-93d70c80-ba59-11e8-9120-01264f862adc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:  3.8.4

**Comment by daishi4u** [comment]
The refresh token can't be refreshed automatically, but I think I know where the problem lies here to detect the expired token. (Why it's not asking to log in again) I will look into it tonight.

**Comment by daishi4u** [comment]
There is a better check in place for an expired refresh token in v3.8.6. It will ask you to login again after it's expired. The access token gets refreshed automatically from the refresh token, but the length of time that a refresh token is valid for depends on settings in your org.

**Comment by julesx** [comment]
3.9.2

i still get the same "expired access/refresh token"

no prompt of any sort to login again, i am forced to restart vs code

**Comment by daishi4u** [comment]
One question, are you only using a single org when this happens or do you have more than one showing up as a green circle in your saved usernames?

**Comment by julesx** [comment]
I do have multiple orgs setup, will check circle state Monday AM

**Comment by julesx** [comment]
VS code left open all weekend
ForceCode side panel shows my two orgs, both green circles
Attempting to save an apex class shows the expired access/refresh token toast
nothing else happens

**Comment by daishi4u** [comment]
OK v3.9.3 covers some login error checking that could possibly fix this.

**Comment by daishi4u** [comment]
I'm no longer pushing changes to this repo. Update to the marketplace version to get the latest and see if the problem still persists. The latest version is 3.9.7
