### ISSUE TITLE
Impossible to make a diff with the server for Lightning component file

### ISSUE THREAD

**Issue by Bartheleway** [daishi4u/ForceCode#91]
**Describe the bug**
Impossible to make a diff with the server for Lightning component file (css, cmp, design, ...).
We can refresh and save so I suppose something is missing.

**To Reproduce**
1. Create a lightning component
2. Open the css file of the lightning component (CmpName.css)
3. Click on ForceCode menu
4. Click on "Diff" option
5. You get the following error :
`
SELECT Body FROM AuraDefinition WHERE NamespacePrefix
       ^
ERROR at Row:1:Column:8
No such column 'Body' on entity 'AuraDefinition'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
`

**Expected behavior**
See a diff between Remote / Local like with Apex class

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 3.8.4

**Additional context**
This may be a feature request as Lightning component is kind of new :)

**Comment by daishi4u** [comment]
Yes, this is actually more of a feature request as I haven't implemented any Diff code for lightning components. They are completely different, so not sure if it can be done at the moment, but I will let you know if I come up with something in the future.

**Comment by daishi4u** [comment]
This is fixed in v3.8.6
