### ISSUE TITLE
Retrieve metadata task never finishes

### ISSUE THREAD

**Issue by ReaperBeats** [daishi4u/ForceCode#93]
**Describe the bug**
Even though metadata is downloaded, the "Retrieve metadata" task keeps running endlessly.

**To Reproduce**
1. Go to ForceCode Menu
2. Click on 'Retrieve Package/Metadata' 
3. Click on 'Retrieve by package.xml' 
4. The operation might run correctly or not, but the Task won't finish.

**Desktop:**
 - OS: Windows10
 - Version 3.8.5

**Comment by daishi4u** [comment]
Are you sure that your package.xml file is correct? I just tried to repro, but mine is working fine.

**Comment by ReaperBeats** [comment]
We had 2 cases:

- On one hand my package had metadata that didnt exist in the environment, so it didnt download anything, but the task didnt finish,
- on the other hand, a colleague had a correct package that downloaded the metadata, but the task still didnt finish.

At the moment we are working with version 3.8.4 and its working fine.

**Comment by daishi4u** [comment]
This is fixed in v3.8.7
