### ISSUE TITLE
'Get current overall code coverage' does not update coverage stats in ForceCode UI.

### ISSUE THREAD

**Issue by cgb-76** [daishi4u/ForceCode#96]
Using the ForceCode menu item 'Get current overall code coverage' downloads and displays the .acov file however, the APEX classes do not update their coverage % based on the downloaded data.

Is this expected?

**Steps to reproduce:**
1. Create APEX class + test class.
2. Clear any coverage data from VS Code so the class reports 0% coverage.
3. Run tests in dev console. Confirm Salesforce shows X% covered.
4. Hit the 'Get current overall code coverage' menu.

**Expected Result:** The file is downloaded. The class reports the same coverage as the developer console.
**Actual Result:** The file is downloaded. Coverage is not updated.

**Comment by cgb-76** [comment]
Running all tests in the test class updates the coverage, but it also appears to have pulled in the coverage for everything else. 
I.e. My coverage was out for classes A, B & C. After running all tests for class A (using the 'here' link in the mouseover on @isTest), my coverage for B & C are also up-to-date.

**Comment by daishi4u** [comment]
This is an expected result. I don't update coverage when pulling the overall, but I suppose it wouldn't be a bad thing to do. I'll add that to the next release.

**Comment by cgb-76** [comment]
Awesome, thanks.

**Comment by daishi4u** [comment]
You're welcome. This is now in v3.9.0
