### ISSUE TITLE
Running the contributed command:'ForceCode.showMenu' failed.

### ISSUE THREAD

**Issue by samuelbliss** [daishi4u/ForceCode#98]
I have Visual Studio Code version 1.27.2 and recently tried to install ForceCode 3.9.0. It 'succeeds' but then when I try to run the force code menu to log in to my org I get this error: "Running the contributed command:'ForceCode.showMenu' failed. "

I have tried uninstalling forcecode, all other extensions, and Visual Studio Code and reinstalled VSCode and just force code and am still getting the error no matter what I do.

Any thoughts?

Desktop:
 - OS: Windows 10
 - Version 1703

**Comment by daishi4u** [comment]
Did you open a folder in vscode before trying to run the command?

**Comment by samuelbliss** [comment]
No I did not! I opened a project and now it's working. That makes sense. Thank you!
